spring:
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
  datasource:
    generate-unique-name: false
    name: tacocloud

taco:
  orders:
    pageSize: 10

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacouser
    password: tacopassword

logging:
  level:
    tacos: WARN
